-- let
-- notacao {} p/ prod types
-- automatic implicit args {} e @funcao
-- patern matching simultaneo (sobre 'tuplas')
-- pattern matching defs em casos eg. ` | x :: xs => ...`
-- pattern matching shorthand
-- type inferences
-- string interp
-- tudo isso no FPIL4